version: '3'
services:
  web:
    image: nginx
    container_name: servicio1
    ports:
      - "8080:80"
   
  php:
    image: phpmyadmin
    container_name: servicio2
    ports:
      - "8082:80"
    # networks:
    #   - red2
  apache:
    image: httpd
    container_name: servicio3
    ports:
      - "8081:80"
  python:
    build: 
      context: ./servidor1
      dockerfile: Dockerfile
    container_name: servicio4
    ports:
      - "8086:5000"
    volumes:
      # ruta del host
      - ./datos:/app/data
      # ruta del contenedor
