version: '3'
services:
  nodo1:
    build:
      dockerfile: Dockerfile
    container_name: nodo1
    volumes:
      - ./entrada:/app/entrada
      - ./salida:/app/salida
    command: sh -c "python mapReduce.py /app/entrada/texto1.txt > /app/salida/texto1.txt"
  nodo2:
    build:
      dockerfile: Dockerfile
    container_name: nodo2
    volumes:
      - ./entrada:/app/entrada
      - ./salida:/app/salida
    command: sh -c "python mapReduce.py /app/entrada/texto2.txt > /app/salida/texto2.txt"
  nodo3:
    build:
      dockerfile: Dockerfile
    container_name: nodo3
    volumes:
      - ./entrada:/app/entrada
      - ./salida:/app/salida
    command: sh -c "python mapReduce.py /app/entrada/texto3.txt > /app/salida/texto3.txt"
  nodo4:
    build:
      dockerfile: Dockerfile
    container_name: nodo4
    volumes:
      - ./entrada:/app/entrada
      - ./salida:/app/salida
    command: sh -c "python mapReduce.py /app/entrada/* > /app/salida/texto4completo.txt"