version: '3'

#Base de datos
services:
    MySQL_master:
        image: mysql:5.7
        container_name: master_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE_NAME: master_db
        ports:
            - "3308:3306"
        command:
            --server-id=1 --log-bin=mysql-bin --log_error=mysql-bin.err --binlog-do-db=replica
    
    MySQL_esclavo:
        image: mysql:5.7
        container_name: slave_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE_NAME: master_db
        ports:
            - "3309:3306"
        command:
            --server-id=2 --log-bin=mysql-bin --log_error=mysql-bin.err --binlog-do-db=replica
            
    PHP_My_Admin:
        image: phpmyadmin
        container_name: php_admin
        ports:
            - "8082:80"
        environment:
            PMA_HOSTS: "MySQL_master, MySQL_esclavo"
            PMA_ARBITRARY: 1